server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      snapshot: false
  server:
    password: "partydemonsecret"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    playerUpdateInterval: 5

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - WEBEMBEDDED
      - TVHTML5EMBEDDED
      - IOS
    oauth:
      enabled: true
      skipInitialization: true
      refreshToken: "1//06M1UhX8oC5lTCgYIARAAGAYSNwF-L9IrR9QeIbFn-GWY7HocwhZnV0VPC2tfTecRsnbTiDa65lszHuZWWIfrowyMu3KNkgl8oW8"

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
