server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "partydemonsecret"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.3"
    snapshot: false

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
